### ISSUE TITLE
Tests with PGI

### ISSUE THREAD

**Issue by andreww** [andreww/fox#56]
In an ideal world we would run CI tests with other compilers. PGI have a community edition that looks like it could be installed on travis. See https://github.com/quixdb/squash/issues/217 for an example and #55 for an outline of doing this with Intel (which looks harder). Would help avoid things like #47.

**Comment by nemequ** [comment]
FWIW, this should be pretty easy with https://github.com/nemequ/pgi-travis.

Intel is hard because their licensing code gets in the way; PGI pretty much lets you do [whatever you want](https://www.pgroup.com/userforum/viewtopic.php?t=5502).

**Comment by andreww** [comment]
That's excellent, I hadn't seen that.

Thanks!

**Comment by andreww** [comment]
Yes - much easer. I now have a branch that tests against pgf90. A fair sprinkling of the test cases segfault or produce memory allocation errors, but that's not a problem with the testing system!
